# Generated by Django 5.2.7 on 2025-11-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='balance_sheets/')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-year', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('non_current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investing_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financing_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Financial Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
