# Generated by Django 5.2.7 on 2025-11-01 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balance_sheets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_balance_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='balance_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='balance_sheets.balancesheet'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('company', 'year', 'quarter')},
        ),
    ]
