# Generated by Django 5.2.7 on 2025-11-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_sheets', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('BALANCE_SHEET', 'Balance Sheet'), ('INCOME_STATEMENT', 'Income Statement / P&L'), ('CASH_FLOW', 'Cash Flow Statement'), ('NOTES', 'Notes to Accounts'), ('RATIOS', 'Financial Ratios'), ('OTHER', 'Other')], max_length=30)),
                ('page_range', models.CharField(help_text="e.g., '5-12' or '15-20'", max_length=50)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('period', models.CharField(blank=True, help_text='Year/Quarter this chunk represents', max_length=50, null=True)),
                ('content', models.TextField(help_text='Extracted text content from this section')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Structured data if applicable')),
                ('confidence', models.FloatField(default=0.0, help_text='Extraction confidence score')),
                ('content_summary', models.TextField(blank=True, help_text='Brief summary of chunk content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='balance_sheets.balancesheet')),
            ],
            options={
                'verbose_name_plural': 'PDF Chunks',
                'ordering': ['start_page', 'section_type'],
                'indexes': [models.Index(fields=['balance_sheet', 'section_type'], name='balance_she_balance_7a33db_idx'), models.Index(fields=['balance_sheet', 'start_page'], name='balance_she_balance_fce53f_idx')],
            },
        ),
    ]
