# Generated by Django 5.2.7 on 2025-11-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_sheets', '0004_pdfchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfchunk',
            name='chunk_type',
            field=models.CharField(choices=[('Table_FS', 'Financial Statement Table'), ('Narrative_Text', 'Narrative Text'), ('Narrative_Note', 'Narrative Note'), ('Narrative_Intro', 'Narrative Introduction'), ('Narrative_General', 'General Narrative')], default='Narrative_General', help_text='Type of chunk content', max_length=30),
        ),
        migrations.AddField(
            model_name='pdfchunk',
            name='page_num',
            field=models.IntegerField(default=1, help_text='Primary page number for this chunk'),
        ),
        migrations.AddField(
            model_name='pdfchunk',
            name='source_title',
            field=models.CharField(blank=True, help_text="Title/source of this chunk (e.g., 'Consolidated Balance Sheet')", max_length=500),
        ),
        migrations.AlterField(
            model_name='pdfchunk',
            name='confidence',
            field=models.FloatField(default=0.85, help_text='Extraction confidence score'),
        ),
        migrations.AlterField(
            model_name='pdfchunk',
            name='page_range',
            field=models.CharField(blank=True, help_text="e.g., '5-12' or '15-20'", max_length=50),
        ),
        migrations.AlterField(
            model_name='pdfchunk',
            name='section_type',
            field=models.CharField(choices=[('BALANCE_SHEET', 'Balance Sheet'), ('INCOME_STATEMENT', 'Income Statement / P&L'), ('CASH_FLOW', 'Cash Flow Statement'), ('NOTES', 'Notes to Accounts'), ('RATIOS', 'Financial Ratios'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
