# Generated by Django 5.2.7 on 2025-11-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_sheets', '0005_pdfchunk_chunk_type_pdfchunk_page_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfchunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list, help_text='Vector embedding for semantic search (RAG)'),
        ),
    ]
